export enum EvoItemRestictions {
  ALL_CLASSES = 0,
  FORGE = 1,
  MELEE = 2,
  MELEE_AGI = 3,
  INT = 5,
  DRUID = 6,
  SWORDSMAN = 7,
  SW_THIEF = 8,
  INI_D_ACO = 10,
  ARCHER = 11,
  CHUNIN = 12,
  SHAPESHIFTER = 13,
  INQUISITOR = 14,
  FORGING_MATERIAL = 15,
  HIGH_TEMPLAR = 16,
  AC_CA_FA = 17,
  TANK = 18,
  ULTIMATE_FORGE = 19,
  TEMPLAR_NINJA = 20,
  NOBLE = 21,
  FAIRY = 22,
  DI = 23,
  TEMPLAR = 24,
  CASTER = 25,
  THIEF = 26,
  WH = 27,
  INITIATE = 28,
  ACOLYTE = 29,
  NINJA = 30,
  PROFESSION = 31,
  AC_CA = 32,
  BARD = 33,
}

export const evoItemRestrictions = {
  [EvoItemRestictions.ALL_CLASSES]: 'All classes',
  [EvoItemRestictions.BARD]: 'Bard only',
  [EvoItemRestictions.FORGE]: 'Forge material',
  [EvoItemRestictions.MELEE]: 'Melee classes only',
  [EvoItemRestictions.MELEE_AGI]: 'Melee agility classes only',
  [EvoItemRestictions.INT]: 'Intelligence classes only',
  [EvoItemRestictions.DRUID]: 'Druid class only',
  [EvoItemRestictions.SWORDSMAN]: 'Swordsman class only',
  [EvoItemRestictions.SW_THIEF]: 'Swordsman, Thief class only',
  [EvoItemRestictions.INI_D_ACO]: 'Initiate, Druid, Acolyte class only',
  [EvoItemRestictions.ARCHER]: 'Archer class only',
  [EvoItemRestictions.CHUNIN]: 'Chunin class only',
  [EvoItemRestictions.SHAPESHIFTER]: 'Shapeshifter class only',
  [EvoItemRestictions.INQUISITOR]: 'Inquisitor class only',
  [EvoItemRestictions.FORGING_MATERIAL]: 'Forging material',
  [EvoItemRestictions.HIGH_TEMPLAR]: 'High Templar class only',
  [EvoItemRestictions.AC_CA_FA]: 'Acolyte, Caster, Fairy class only',
  [EvoItemRestictions.TANK]: 'Tank classes only',
  [EvoItemRestictions.ULTIMATE_FORGE]: 'Ultimate forge material',
  [EvoItemRestictions.TEMPLAR_NINJA]: 'Templar, Ninja class only',
  [EvoItemRestictions.NOBLE]: 'Noble class only',
  [EvoItemRestictions.FAIRY]: 'Fairy class only',
  [EvoItemRestictions.DI]: 'Demon Incarnate class only',
  [EvoItemRestictions.TEMPLAR]: 'Templar class only',
  [EvoItemRestictions.CASTER]: 'Caster class only',
  [EvoItemRestictions.THIEF]: 'Thief class only',
  [EvoItemRestictions.WH]: 'Witch Hunter class only',
  [EvoItemRestictions.INITIATE]: 'Initiate class only',
  [EvoItemRestictions.ACOLYTE]: 'Acolyte class only',
  [EvoItemRestictions.NINJA]: 'Ninja class only',
  [EvoItemRestictions.PROFESSION]: 'Profession item',
  [EvoItemRestictions.AC_CA]: 'Acolyte, Caster class only',
};
